//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaOrdering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCheckOut
    {
        public int cid { get; set; }
        public string cname { get; set; }
        public long contact { get; set; }
        public Nullable<int> orders { get; set; }
        public Nullable<long> total { get; set; }
    }
}
